#PATHS

RAW_DATA_DIR : 'data/raw/'
PROC_DATA_DIR : 'data/processed/'
INTERIM_DATA_DIR : 'data/interim/'
MODEL_SAVE_DIR : 'models_/'
VIS_PREDS_DIR : 'data/vis/'
CMP_FMT : '.tar.bz2'

GMU_DATA_PACKED : 'data/raw/speech-accent-archive.zip'
GMU_DATA_INFO : 'data/raw/speech-accent-archive/speakers_all.csv'
GMU_DATA : 'data/raw/speech-accent-archive/recordings/recordings/'
GMU_ACCENT_COUNT : 4
AUDIO_READ_FORMAT : '.mp3'
AUDIO_WRITE_FORMAT : '.wav'
SAMPLING_RATE : 16000 #Hz
WINDOW_SIZE : 25 #ms
WINDOW_STEP : 10 #ms
MEL_CHANNELS : 40
SMOOTHING_WSIZE : 30
SMOOTHING_LENGTH : 6
DBFS : -30