#PATHS

RAW_DATA_DIR : 'data/raw/'
PROC_DATA_DIR : 'data/processed/'
INTERIM_DATA_DIR : 'data/interim/'
MODEL_SAVE_DIR : 'models_/'
VIS_PREDS_DIR : 'data/vis/'
CMP_FMT : '.tar.bz2'
RUNS_DIR : 'runs/'

GMU_DATA_PACKED : 'data/raw/speech-accent-archive.zip'
GMU_DATA_INFO : 'data/raw/speech-accent-archive/speakers_all.csv'
GMU_DATA : 'data/raw/speech-accent-archive/recordings/recordings/'
GMU_ACCENT_COUNT : 4
AUDIO_READ_FORMAT_GMU : '.mp3'


TIMIT_DATA_PACKED : 'data/raw/TIMIT.zip'
TIMIT_DATA_INFO : 'data/raw/TIMIT/README.DOC'
TIMIT_DATA_TRAIN : 'data/raw/TIMIT/TRAIN'
TIMIT_DATA_TEST : 'data/raw/TIMIT/TEST'
TIMIT_ACCENT_COUNT : 8
AUDIO_READ_FORMAT_TIMIT : '.WAV'
VAD_MODE : 3

AUDIO_WRITE_FORMAT : '.wav'
SAMPLING_RATE : 16000 #Hz
WINDOW_SIZE : 64 #ms
WINDOW_STEP : 16 #ms
MEL_CHANNELS : 80
SMOOTHING_WSIZE : 30
SMOOTHING_LENGTH : 6
DBFS : -30
HIDDEN_SIZE : 512 #128
EMBEDDING_SIZE : 512
PROJECTION_SIZE : 64
NUM_LAYERS : 3
SLIDING_WIN_SIZE : 64 # frames # use 64 for 1dconv and 160 for lstm
SLIDING_WIN_OVERLAP : 0.5
UTTR_COUNT : 5
ACC_COUNT : 4
BATCH_SIZE : 20 # 4 accents total 8x4=32 tensors
VAL_LOSS_COUNT : 1